pipeline {
    agent any
 
    tools {
        maven 'Maven3'
        jdk 'jdk21'
    }
 
    stages {
 
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Himanshusingh26202/Testing-Wipro.git'
            }
        }
 
 
 
        stage('Build') {
            steps {
                dir('CucumberBBD') {
                    bat 'mvn clean'
                }
            }
        }
 
        stage('Compile') {
            steps {
                dir('CucumberBBD') {
                    bat 'mvn compile'
                }
            }
        }
 
        stage('Test') {
            steps {
                dir('CucumberBBD') {
                    bat 'mvn test'
                }
            }
        }
 
        stage('Package') {
            steps {
                dir('CucumberBBD') {
                    bat 'mvn package'
                }
            }
            
        }
               stage('Docker Build') {
    steps {
		dir('CucumberBBD') {
        bat 'docker build -t cucumber-framework .'
    }
    }
}
 
stage('Docker Run') {
    steps {
       dir('CucumberBBD') {
        bat 'docker run --rm cucumber-framework'
    }
    }
}
  stage('Build Docker Image') {
            steps {
				 dir('CucumberBBD') {
                bat 'docker build -t cucumber-project .'
            }
        }
       }
 
    }
 
    post {
		  always {
            junit allowEmptyResults: true,
                  testResults: 'CucumberBDD/target/junitreports/*.xml'

            archiveArtifacts artifacts: 'CucumberBDD/target/*/.*',
                             fingerprint: true
        }
        success {
            echo 'Build Successful'
        }
 
        failure {
            echo 'Build Failed'
        }
    }
}