pipeline {
    agent any
 
    tools {
        maven 'Maven3'
    }
 
    stages {
 
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Himanshusingh26202/Testing-Wipro.git'
            }
        }
 
 
 
        stage('Build') {
            steps {
                dir('CucumberBBD') {
                    bat 'mvn clean'
                }
            }
        }
 
        stage('Compile') {
            steps {
                dir('CucumberBBD') {
                    bat 'mvn compile'
                }
            }
        }
 
        stage('Test') {
            steps {
                dir('CucumberBBD') {
                    bat 'mvn test'
                }
            }
        }
 
        stage('Package') {
            steps {
                dir('CucumberBBD') {
                    bat 'mvn package'
                }
            }
        }
    }
 
    post {
        success {
            echo 'Build Successful'
        }
 
        failure {
            echo 'Build Failed'
        }
    }
}